server:
  port: ${PORT:8081}
logging:
  level:
    root: INFO
spring:
  datasource:
    platform: h2
    jdbc-url: jdbc-url=jdbc:h2:mem:test
  h2:
    console:
      enabled: true
      path: /h2-console
